services:
  oracle_db:
    image: gvenzl/oracle-free:23-slim
    platform: linux/arm64
    container_name: oracle_db_container
    environment:
      ORACLE_PASSWORD: apimpass
      ORACLE_DATABASE: apim_db
    ports:
      - "1521:1521"
    restart: unless-stopped
    volumes:
      - ./dbscripts:/scripts
