version: '3.8'
services:
  apim_db:
    image: mcr.microsoft.com/azure-sql-edge
    container_name: apim_db_container
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "RootPass123!"
      MSSQL_PID: "Developer"
    ports:
      - "1433:1433"
    volumes:
      - ./init:/docker-entrypoint-initdb.d

  shared_db:
    image: mcr.microsoft.com/azure-sql-edge
    container_name: shared_db_container
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "RootPass123!"
      MSSQL_PID: "Developer"
    ports:
      - "1434:1433"
    volumes:
      - ./init:/docker-entrypoint-initdb.d
